/* Generated By:JJTree: Do not edit this line. ASTVARS2.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package visitorGrammar;

public
class ASTVARS2 extends SimpleNode {
  public ASTVARS2(int id) {
    super(id);
  }

  public ASTVARS2(visitorGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(visitorGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db175d2d5a16fb5c17c3b9af43cc66ec (do not edit this line) */
