/* Generated By:JavaCC: Do not edit this line. visitorGrammarTreeConstants.java Version 6.0_1 */
package visitorGrammar;

public interface visitorGrammarTreeConstants
{
  public int JJTS = 0;
  public int JJTVOID = 1;
  public int JJTDECL = 2;
  public int JJTX = 3;
  public int JJTVARS = 4;
  public int JJTVARS2 = 5;
  public int JJTLINES2 = 6;
  public int JJTASSN = 7;
  public int JJTY = 8;
  public int JJTZ = 9;
  public int JJTTERM2 = 10;
  public int JJTFACTOR = 11;
  public int JJTIFSTMT = 12;
  public int JJTTEST = 13;
  public int JJTQ = 14;


  public String[] jjtNodeName = {
    "S",
    "void",
    "DECL",
    "X",
    "VARS",
    "VARS2",
    "LINES2",
    "ASSN",
    "Y",
    "Z",
    "TERM2",
    "FACTOR",
    "IFSTMT",
    "TEST",
    "Q",
  };
}
/* JavaCC - OriginalChecksum=85b3fef0ed21150ed00bd622c255291a (do not edit this line) */
