/* Generated By:JavaCC: Do not edit this line. visitorGrammarVisitor.java Version 6.0_1 */
package visitorGrammar;

public interface visitorGrammarVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTS node, Object data);
  public Object visit(ASTDECL node, Object data);
  public Object visit(ASTX node, Object data);
  public Object visit(ASTVARS node, Object data);
  public Object visit(ASTVARS2 node, Object data);
  public Object visit(ASTLINES2 node, Object data);
  public Object visit(ASTASSN node, Object data);
  public Object visit(ASTY node, Object data);
  public Object visit(ASTZ node, Object data);
  public Object visit(ASTTERM2 node, Object data);
  public Object visit(ASTFACTOR node, Object data);
  public Object visit(ASTIFSTMT node, Object data);
  public Object visit(ASTTEST node, Object data);
  public Object visit(ASTQ node, Object data);
}
/* JavaCC - OriginalChecksum=63b872a1077bfa3b3b1060cd63bd799f (do not edit this line) */
