/* Generated By:JavaCC: Do not edit this line. grammarTreeConstants.java Version 6.0_1 */
public interface grammarTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTS = 1;
  public int JJTDECLS = 2;
  public int JJTDECLS2 = 3;
  public int JJTDECL = 4;
  public int JJTX = 5;
  public int JJTVARS = 6;
  public int JJTVARS2 = 7;
  public int JJTLINES = 8;
  public int JJTLINES2 = 9;
  public int JJTSTMT = 10;
  public int JJTASSN = 11;
  public int JJTY = 12;
  public int JJTY2 = 13;
  public int JJTEXPR = 14;
  public int JJTEXPR2 = 15;
  public int JJTZ = 16;
  public int JJTTERM = 17;
  public int JJTTERM2 = 18;
  public int JJTFACTOR = 19;
  public int JJTIFSTMT = 20;
  public int JJTTEST = 21;
  public int JJTTEST2 = 22;
  public int JJTQ = 23;


  public String[] jjtNodeName = {
    "Input",
    "S",
    "DECLS",
    "DECLS2",
    "DECL",
    "X",
    "VARS",
    "VARS2",
    "LINES",
    "LINES2",
    "STMT",
    "ASSN",
    "Y",
    "Y2",
    "EXPR",
    "EXPR2",
    "Z",
    "TERM",
    "TERM2",
    "FACTOR",
    "IFSTMT",
    "TEST",
    "TEST2",
    "Q",
  };
}
/* JavaCC - OriginalChecksum=392a5d63032c841411554c553ea842fa (do not edit this line) */
